export const I1 = [
  {
    name: "ADS",
    time: "8:00am-9:00am",
    faculty: "MM",
    day: "Monday",
  },
  {
    name: "PBC",
    time: "09:00am-10:00am",
    faculty: "B",
    day: "Monday",
  },
  {
    name: "CNS",
    time: "10:00am-11:00am",
    faculty: "RM",
    day: "Monday",
  },
  {
    name: "DWM",
    time: "11:30am-12:30pm",
    faculty: "VS",
    day: "Monday",
  },
  {
    name: "CG",
    time: "12:30pm-1:30pm",
    faculty: "NK",
    day: "Monday",
  },
  {
    name: "SA",
    time: "12:30pm-1:30pm",
    faculty: "ARJ",
    day: "Monday",
  },
  {
    name: "ADS Laboratory",
    time: "2:00pm-4:00pm",
    faculty: "AP",
    day: "Monday",
  },
  {
    name: "DWM Laboratory",
    time: "2:00pm-4:00pm",
    faculty: "VS",
    day: "Monday",
  },
  {
    name: "Honors",
    time: "8:00am-10:00am",
    faculty: "AJ",
    day: "Tuesday",
  },
  {
    name: "DWM",
    time: "11:00am-12:00pm",
    faculty: "VS",
    day: "Tuesday",
  },
  {
    name: "DWM Laboratory",
    time: "12:00pm-2:00pm",
    faculty: "VS",
    day: "Tuesday",
  },
  {
    name: "CNS Laboratory",
    time: "12:00pm-2:00pm",
    faculty: "RS",
    day: "Tuesday",
  },
  {
    name: "AI",
    time: "2:30pm-3:30pm",
    faculty: "PS",
    day: "Tuesday",
  },
  {
    name: "CNS",
    time: "3:30pm-4:30pm",
    faculty: "RM",
    day: "Tuesday",
  },
  {
    name: "ADS",
    time: "4:30pm-5:30pm",
    faculty: "MM",
    day: "Tuesday",
  },
  {
    name: "SA Laboratory",
    time: "8:00am-10:00am",
    faculty: "V",
    day: "Wednesday",
  },
  {
    name: "AI Laboratory",
    time: "8:00am-10:00am",
    faculty: "PS",
    day: "Wednesday",
  },
  {
    name: "CNS",
    time: "10:30am-11:30am",
    faculty: "RM",
    day: "Wednesday",
  },
  {
    name: "SA",
    time: "11:30am-12:30pm",
    faculty: "ARJ",
    day: "Wednesday",
  },
  {
    name: "MINORS",
    time: "3:00pm-5:00pm",
    faculty: "Other",
    day: "Wednesday",
  },
  {
    name: "PBC Laboratory",
    time: "8:00am-10:00am",
    faculty: "KT",
    day: "Thursday",
  },
  {
    name: "SA Laboratory",
    time: "8:00am-10:00am",
    faculty: "SM",
    day: "Thursday",
  },
  {
    name: "SA",
    time: "10:00am-11:00am",
    faculty: "ARJ",
    day: "Thursday",
  },
  {
    name: "AI",
    time: "11:00am-12:00pm",
    faculty: "PS",
    day: "Thursday",
  },
  {
    name: "ADS",
    time: "12:30pm-1:30pm",
    faculty: "MM",
    day: "Thursday",
  },
  {
    name: "PBC",
    time: "1:30pm-2:30pm",
    faculty: "KT",
    day: "Thursday",
  },
  {
    name: "CG",
    time: "2:30pm-3:30pm",
    faculty: "NK",
    day: "Thursday",
  },
  {
    name: "CG Laboratory",
    time: "3:30pm-5:30pm",
    faculty: "NK",
    day: "Thursday",
  },
  {
    name: "Honors",
    time: "3:30pm-5:30pm",
    faculty: "PS",
    day: "Friday",
  },
  {
    name: "CNS Laboratory",
    time: "8:00am-10:00am",
    faculty: "RM",
    day: "Saturday",
  },
  {
    name: "PBC Laboratory",
    time: "8:00am-10:00am",
    //TODO
    faculty: "VI",
    day: "Saturday",
  },
  {
    name: "AI",
    time: "10:00am-11:00am",
    faculty: "PS",
    day: "Saturday",
  },
  {
    name: "DWM",
    time: "11:00am-12:00pm",
    faculty: "VS",
    day: "Saturday",
  },
  {
    name: "AI Laboratory",
    time: "12:30pm-2:30pm",
    faculty: "PS",
    day: "Saturday",
  },
  {
    name: "ADS Laboratory",
    time: "12:30pm-2:30pm",
    faculty: "MM",
    day: "Saturday",
  },
  {
    name: "CG",
    time: "2:30pm-3:30pm",
    faculty: "NK",
    day: "Saturday",
  },
  {
    name: "MINORS",
    time: "3:30pm-5:30pm",
    faculty: "Other",
    day: "Saturday",
  },
].map((classItem, index) => ({ ...classItem, id: index + 1 }));
