export const I2 = [
  {
    name: "CNS",
    time: "8:00am-9:00am",
    faculty: "SC",
    day: "Monday",
  },
  {
    name: "ADS",
    time: "09:00am-10:00am",
    faculty: "AP",
    day: "Monday",
  },
  {
    name: "SA Laboratory",
    time: "10:00am-12:00pm",
    faculty: "PS",
    day: "Monday",
  },
  {
    name: "PBC Laboratory",
    time: "10:00am-12:00pm",
    faculty: "SR",
    day: "Monday",
  },
  {
    name: "SA",
    time: "12:30pm-1:30pm",
    faculty: "PS",
    day: "Monday",
  },
  {
    name: "CG",
    time: "12:30pm-1:30pm",
    faculty: "NK",
    day: "Monday",
  },
  {
    name: "AI",
    time: "1:30pm-2:30pm",
    faculty: "SP",
    day: "Monday",
  },
  {
    name: "Honors",
    time: "8:00am-10:00am",
    faculty: "AJ",
    day: "Tuesday",
  },
  {
    name: "CNS",
    time: "11:00am-12:00pm",
    faculty: "SC",
    day: "Tuesday",
  },
  {
    name: "CNS Laboratory",
    time: "12:00pm-2:00pm",
    faculty: "SC",
    day: "Tuesday",
  },
  {
    name: "ADS Laboratory",
    time: "12:00pm-2:00pm",
    faculty: "NA",
    day: "Tuesday",
  },
  {
    name: "PBC",
    time: "2:30pm-3:30pm",
    faculty: "SR",
    day: "Tuesday",
  },
  {
    name: "AI",
    time: "3:30pm-4:30pm",
    faculty: "SP",
    day: "Tuesday",
  },
  {
    name: "ADS",
    time: "4:30pm-5:30pm",
    faculty: "AP",
    day: "Tuesday",
  },
  {
    name: "Minors",
    time: "3:30pm-5:30pm",
    faculty: "Other",
    day: "Wednesday",
  },
  {
    name: "PBC Laboratory",
    time: "8:00am-10:00am",
    faculty: "API",
    day: "Thursday",
  },
  {
    name: "SA Laboratory",
    time: "8:00am-10:00am",
    faculty: "V",
    day: "Thursday",
  },
  {
    name: "DWM",
    time: "10:00am-11:00am",
    faculty: "VS",
    day: "Thursday",
  },
  {
    name: "PBC",
    time: "11:00am-12:00pm",
    faculty: "SR",
    day: "Thursday",
  },
  {
    name: "DWM Laboratory",
    time: "12:30pm-2:30pm",
    faculty: "SM",
    day: "Thursday",
  },
  {
    name: "AI Laboratory",
    time: "12:30pm-2:30pm",
    faculty: "SP",
    day: "Thursday",
  },
  {
    name: "CG",
    time: "2:30pm-3:30pm",
    faculty: "NK",
    day: "Thursday",
  },
  {
    name: "CG Laboratory",
    time: "3:30pm-5:30pm",
    faculty: "NK",
    day: "Thursday",
  },
  {
    name: "AI Laboratory",
    time: "8:00am-10:00am",
    faculty: "SP",
    day: "Friday",
  },
  {
    name: "CNS Laboratory",
    time: "8:00am-10:00am",
    faculty: "SC",
    day: "Friday",
  },
  {
    name: "DWM",
    time: "10:00am-11:00am",
    faculty: "VS",
    day: "Friday",
  },
  {
    name: "CNS",
    time: "11:30am-12:30pm",
    faculty: "SC",
    day: "Friday",
  },
  {
    name: "SA",
    time: "12:30pm-1:30pm",
    faculty: "PS",
    day: "Friday",
  },
  {
    name: "Honors",
    time: "3:30pm-5:30pm",
    faculty: "PS",
    day: "Friday",
  },
  {
    name: "ADS",
    time: "9:00am-10:00am",
    faculty: "AP",
    day: "Saturday",
  },
  {
    name: "ADS Laboratory",
    time: "10:00am-12:00pm",
    faculty: "AP",
    day: "Saturday",
  },
  {
    name: "DWM Laboratory",
    time: "10:00am-12:00pm",
    faculty: "SM",
    day: "Saturday",
  },
  {
    name: "AI",
    time: "12:30pm-1:30pm",
    faculty: "SP",
    day: "Saturday",
  },
  {
    name: "DWM",
    time: "1:30pm-2:30pm",
    faculty: "VS",
    day: "Saturday",
  },
  {
    name: "CG",
    time: "2:30pm-3:30pm",
    faculty: "NK",
    day: "Saturday",
  },
  {
    name: "SA",
    time: "2:30pm-3:30pm",
    faculty: "PS",
    day: "Saturday",
  },
  {
    name: "Minors",
    time: "3:30pm-5:30pm",
    faculty: "Other",
    day: "Saturday",
  },
].map((classItem, index) => ({ ...classItem, id: index + 1 }));
